### ISSUE TITLE
Unable to parse tuple response

### ISSUE THREAD

**Issue by wafcio** [q9f/eth.rb#266] opened 2024-04-03 15:52 UTC
Response from JSON API in tuple format doesn't work and fails every time.

The problem is located here: https://github.com/q9f/eth.rb/blob/main/lib/eth/abi.rb#L79
```
Type.parse(t)
```
should have a second argument - components; otherwise, for a tuple, the expectation is raised.

```
undefined method `none?' for nil
```

You can check it by calling Ethereum contract `0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9`, method: "getReserveData", argument "0xdAC17F958D2ee523a2206206994597C13D831ec7"

**Comment by q9f** [comment] 2024-04-16 15:03
duplicate of #102 

decoding tuples is not implemented unfortunately. maybe some day we can integrate the new abi decoder written by @wuminzhe - maybe take a look?

https://github.com/wuminzhe/abi_coder_rb

**Closed by q9f** 2024-04-16 15:03 UTC
Labels: duplicate
